# Generated by Django 5.0.6 on 2025-01-18 03:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='主題名稱')),
                ('description', models.TextField(blank=True, null=True, verbose_name='主題描述')),
                ('image', models.ImageField(blank=True, null=True, upload_to='themes/', verbose_name='主題圖片')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '主題',
                'verbose_name_plural': '主題',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='活動名稱')),
                ('description', models.TextField(verbose_name='活動描述')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='活動地點')),
                ('start_date', models.DateField(verbose_name='開始日期')),
                ('end_date', models.DateField(verbose_name='結束日期')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='價格')),
                ('capacity', models.PositiveIntegerField(default=0, verbose_name='容納人數')),
                ('image', models.ImageField(blank=True, null=True, upload_to='activities/', verbose_name='活動圖片')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='theme_entertainment.theme', verbose_name='主題')),
            ],
            options={
                'verbose_name': '活動',
                'verbose_name_plural': '活動',
                'ordering': ['-start_date', '-created_at'],
            },
        ),
    ]
