# Generated by Django 5.0.6 on 2025-01-26 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme_entertainment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtCultureActivity',
            fields=[
                ('uid', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='活動唯一識別碼')),
                ('activity_name', models.CharField(max_length=255, verbose_name='活動名稱')),
                ('performer', models.CharField(blank=True, max_length=255, null=True, verbose_name='演出單位')),
                ('description', models.TextField(blank=True, null=True, verbose_name='簡介說明')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='圖片連結')),
                ('organizer', models.CharField(blank=True, max_length=255, null=True, verbose_name='主辦單位')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='活動起始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='活動結束日期')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='地址')),
                ('venue_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='場地名稱')),
                ('is_ticketed', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True, verbose_name='是否售票')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='緯度')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='經度')),
                ('ticket_price', models.CharField(blank=True, max_length=100, null=True, verbose_name='票價')),
            ],
        ),
        migrations.CreateModel(
            name='CulturalActivity',
            fields=[
                ('uid', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='活動唯一識別碼')),
                ('activity_name', models.CharField(max_length=255, verbose_name='活動名稱')),
                ('performer', models.CharField(blank=True, max_length=255, null=True, verbose_name='演出單位')),
                ('description', models.TextField(blank=True, null=True, verbose_name='簡介說明')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='圖片連結')),
                ('organizer', models.CharField(blank=True, max_length=255, null=True, verbose_name='主辦單位')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='活動起始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='活動結束日期')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='地址')),
                ('venue_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='場地名稱')),
                ('is_ticketed', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True, verbose_name='是否售票')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='緯度')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='經度')),
                ('ticket_price', models.CharField(blank=True, max_length=100, null=True, verbose_name='票價')),
            ],
        ),
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('activity_name', models.CharField(max_length=255, verbose_name='活動名稱')),
                ('description', models.TextField(blank=True, null=True, verbose_name='簡介說明')),
                ('location', models.CharField(max_length=255, verbose_name='活動地點')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='電話')),
                ('organizer', models.CharField(blank=True, max_length=255, null=True, verbose_name='主辦單位')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='活動起始時間')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='活動結束時間')),
                ('url', models.URLField(blank=True, null=True, verbose_name='活動網址')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='緯度')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='經度')),
                ('transport_info', models.TextField(blank=True, null=True, verbose_name='交通資訊')),
                ('parking_info', models.TextField(blank=True, null=True, verbose_name='停車資訊')),
                ('cost', models.CharField(blank=True, max_length=100, null=True, verbose_name='費用')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='備註')),
                ('region', models.CharField(blank=True, max_length=255, null=True, verbose_name='所在區域')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='圖片連結')),
            ],
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='Theme',
        ),
    ]
