# Generated by Django 5.1.6 on 2025-02-20 16:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('theme_entertainment', '0002_artcultureactivity_culturalactivity_festival_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CultureActivity',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uid', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='唯一識別碼')),
                ('activity_name', models.CharField(max_length=500, verbose_name='活動名稱')),
                ('description', models.TextField(blank=True, null=True, verbose_name='活動描述')),
                ('organizer', models.CharField(blank=True, max_length=200, null=True, verbose_name='主辦單位')),
                ('address', models.TextField(blank=True, null=True, verbose_name='地址')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='開始時間')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='結束時間')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='地點')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='緯度')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='經度')),
                ('ticket_info', models.TextField(blank=True, null=True, verbose_name='票價資訊')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='圖片網址')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='建立時間')),
                ('performer', models.CharField(blank=True, max_length=200, verbose_name='演出單位')),
                ('venue_name', models.CharField(blank=True, max_length=200, verbose_name='場地名稱')),
                ('is_free', models.BooleanField(default=True, verbose_name='是否免費')),
                ('source', models.CharField(default='文化部', max_length=50, verbose_name='資料來源')),
            ],
            options={
                'verbose_name': '文化部活動',
                'verbose_name_plural': '文化部活動',
                'db_table': 'theme_culture_activities',
            },
        ),
        migrations.CreateModel(
            name='ImportDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_date', models.DateTimeField()),
                ('timezone_type', models.IntegerField()),
                ('timezone', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': '資料匯入時間',
                'verbose_name_plural': '資料匯入時間',
                'db_table': 'theme_import_dates',
            },
        ),
        migrations.CreateModel(
            name='NewTaipeiActivity',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uid', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='唯一識別碼')),
                ('activity_name', models.CharField(max_length=500, verbose_name='活動名稱')),
                ('description', models.TextField(blank=True, null=True, verbose_name='活動描述')),
                ('organizer', models.CharField(blank=True, max_length=200, null=True, verbose_name='主辦單位')),
                ('address', models.TextField(blank=True, null=True, verbose_name='地址')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='開始時間')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='結束時間')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='地點')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='緯度')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='經度')),
                ('ticket_info', models.TextField(blank=True, null=True, verbose_name='票價資訊')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='圖片網址')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='建立時間')),
                ('activity_id', models.CharField(max_length=100, unique=True, verbose_name='活動ID')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='活動類別')),
                ('venue_phone', models.CharField(blank=True, max_length=50, verbose_name='場地電話')),
                ('transportation', models.TextField(blank=True, verbose_name='交通說明')),
                ('related_link', models.URLField(blank=True, max_length=500, verbose_name='相關連結')),
                ('source', models.CharField(default='新北市', max_length=50, verbose_name='資料來源')),
            ],
            options={
                'verbose_name': '新北市活動',
                'verbose_name_plural': '新北市活動',
                'db_table': 'theme_newtaipei_activities',
            },
        ),
        migrations.CreateModel(
            name='QueryEventRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('display_order', models.IntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': '查詢結果與活動關聯',
                'verbose_name_plural': '查詢結果與活動關聯',
                'db_table': 'theme_query_event_relations',
            },
        ),
        migrations.CreateModel(
            name='QueryResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_timestamp', models.CharField(max_length=50)),
                ('limit_count', models.IntegerField()),
                ('offset_count', models.IntegerField()),
                ('total_count', models.IntegerField()),
                ('sort_order', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': '查詢結果',
                'verbose_name_plural': '查詢結果',
                'db_table': 'theme_query_results',
            },
        ),
        migrations.CreateModel(
            name='TaipeiActivity',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uid', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='唯一識別碼')),
                ('activity_name', models.CharField(max_length=500, verbose_name='活動名稱')),
                ('description', models.TextField(blank=True, null=True, verbose_name='活動描述')),
                ('organizer', models.CharField(blank=True, max_length=200, null=True, verbose_name='主辦單位')),
                ('address', models.TextField(blank=True, null=True, verbose_name='地址')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='開始時間')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='結束時間')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='地點')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='緯度')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='經度')),
                ('ticket_info', models.TextField(blank=True, null=True, verbose_name='票價資訊')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='圖片網址')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='建立時間')),
                ('data_sn', models.CharField(max_length=100, unique=True, verbose_name='資料序號')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='聯絡人')),
                ('contact_phone', models.CharField(blank=True, max_length=50, verbose_name='聯絡電話')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='聯絡Email')),
                ('registration_method', models.CharField(blank=True, max_length=200, verbose_name='報名方式')),
                ('participant_limit', models.CharField(blank=True, max_length=100, verbose_name='人數限制')),
                ('categories', models.JSONField(blank=True, default=list, verbose_name='活動類別')),
                ('source', models.CharField(default='台北市', max_length=50, verbose_name='資料來源')),
            ],
            options={
                'verbose_name': '台北市活動',
                'verbose_name_plural': '台北市活動',
                'db_table': 'theme_taipei_activities',
            },
        ),
        migrations.CreateModel(
            name='TFAMActivity',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uid', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='唯一識別碼')),
                ('activity_name', models.CharField(max_length=500, verbose_name='活動名稱')),
                ('description', models.TextField(blank=True, null=True, verbose_name='活動描述')),
                ('organizer', models.CharField(blank=True, max_length=200, null=True, verbose_name='主辦單位')),
                ('address', models.TextField(blank=True, null=True, verbose_name='地址')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='開始時間')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='結束時間')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='地點')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='緯度')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='經度')),
                ('ticket_info', models.TextField(blank=True, null=True, verbose_name='票價資訊')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='圖片網址')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='建立時間')),
                ('activity_type', models.CharField(choices=[('activity', '一般活動'), ('exhibition', '展覽')], default='activity', max_length=20, verbose_name='活動類型')),
                ('content', models.TextField(verbose_name='內容')),
                ('link', models.URLField(max_length=500, verbose_name='連結')),
                ('publishing_unit', models.CharField(max_length=100, verbose_name='發布單位')),
                ('source', models.CharField(default='北美館', max_length=50, verbose_name='資料來源')),
            ],
            options={
                'verbose_name': '北美館活動',
                'verbose_name_plural': '北美館活動',
                'db_table': 'theme_tfam_activities',
            },
        ),
        migrations.DeleteModel(
            name='ArtCultureActivity',
        ),
        migrations.DeleteModel(
            name='CulturalActivity',
        ),
        migrations.DeleteModel(
            name='Festival',
        ),
        migrations.AddField(
            model_name='queryeventrelation',
            name='query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theme_entertainment.queryresult'),
        ),
        migrations.AddIndex(
            model_name='tfamactivity',
            index=models.Index(fields=['activity_type'], name='theme_tfam__activit_9d382b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='queryeventrelation',
            unique_together={('query', 'content_type', 'object_id')},
        ),
    ]
