# Generated by Django 5.0.6 on 2025-01-27 09:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_system', '0002_alter_comment_author_alter_post_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='標籤名稱')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='標籤圖標')),
                ('description', models.TextField(blank=True, verbose_name='標籤描述')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='創建時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '標籤',
                'verbose_name_plural': '標籤管理',
                'ordering': ['-created_at'],
            },
        ),
    ]
