# Generated by Django 5.0.6 on 2025-02-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_system', '0003_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='forum_system.tag', verbose_name='標籤'),
        ),
    ]
