# Generated by Django 5.1.6 on 2025-03-15 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_system', '0003_alter_comment_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_ai_generated',
            field=models.BooleanField(default=False, verbose_name='AI生成'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='是否公開'),
        ),
    ]
