# Generated by Django 5.1.6 on 2025-03-15 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_system', '0004_post_is_ai_generated_post_is_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_ai_generated',
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_public',
        ),
    ]
