# Generated by Django 5.1.1 on 2025-01-08 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0002_yourmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YourModel',
        ),
    ]
