# Generated by Django 5.1.6 on 2025-03-13 22:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='電子郵件')),
                ('code', models.CharField(max_length=6, verbose_name='驗證碼')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('expires_at', models.DateTimeField(verbose_name='過期時間')),
                ('is_used', models.BooleanField(default=False, verbose_name='是否已使用')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reset_codes', to=settings.AUTH_USER_MODEL, verbose_name='用戶')),
            ],
            options={
                'verbose_name': '密碼重置驗證碼',
                'verbose_name_plural': '密碼重置驗證碼',
                'ordering': ['-created_at'],
            },
        ),
    ]
