# Generated by Django 5.1.6 on 2025-03-16 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password_reset', '0002_passwordresettoken_delete_passwordresetcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresettoken',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='驗證碼'),
        ),
    ]
