# Generated by Django 5.0.6 on 2025-01-16 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_system', '0002_remove_product_image_product_image_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, unique=True, verbose_name='訂單編號')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='總金額')),
                ('status', models.CharField(choices=[('pending', '待付款'), ('paid', '已付款'), ('shipped', '已出貨'), ('completed', '已完成'), ('cancelled', '已取消')], max_length=20, verbose_name='訂單狀態')),
                ('shipping_address', models.TextField(verbose_name='收貨地址')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='聯絡電話')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_orders', to=settings.AUTH_USER_MODEL, verbose_name='購買者')),
            ],
            options={
                'verbose_name': '訂單',
                'verbose_name_plural': '訂單',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='數量')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='購買價格')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shopping_system.order', verbose_name='訂單')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='shopping_system.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '訂單項目',
                'verbose_name_plural': '訂單項目',
            },
        ),
    ]
