# Generated by Django 5.1.1 on 2025-03-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_system', '0002_add_note_field_to_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(max_length=30, unique=True, verbose_name='訂單編號'),
        ),
    ]
