# Generated by Django 5.1.1 on 2025-03-13 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_system', '0003_alter_order_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shopping_system.categorydisplay', verbose_name='產品類型'),
        ),
    ]
