# Generated by Django 5.1.1 on 2025-03-15 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_system', '0004_product_product_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='圖片')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='替代文字')),
                ('is_primary', models.BooleanField(default=False, verbose_name='是否主圖')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shopping_system.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '產品圖片',
                'verbose_name_plural': '產品圖片',
                'ordering': ['-is_primary', 'id'],
            },
        ),
    ]
