# Generated by Django 5.1.6 on 2025-03-19 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_system', '0005_productimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='contact_phone',
            new_name='shipping_phone',
        ),
        migrations.RemoveField(
            model_name='order',
            name='note',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('credit_card', '信用卡'), ('atm', 'ATM轉帳'), ('line_pay', 'LINE Pay')], default='credit_card', max_length=20, verbose_name='付款方式'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_name',
            field=models.CharField(default='', max_length=100, verbose_name='收件人姓名'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_note',
            field=models.TextField(blank=True, default='', verbose_name='訂單備註'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='訂單編號'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shopping_orders', to=settings.AUTH_USER_MODEL, verbose_name='購買者'),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
