# Generated by Django 5.1.6 on 2025-03-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_system', '0006_rename_contact_phone_order_shipping_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_info',
            field=models.JSONField(blank=True, null=True, verbose_name='付款資訊'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('credit_card', '信用卡'), ('atm', 'ATM轉帳'), ('line_pay', 'LINE Pay'), ('ecpay', '綠界金流')], default='credit_card', max_length=20, verbose_name='付款方式'),
        ),
    ]
