# Generated by Django 5.1.6 on 2025-03-19 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_system', '0007_order_payment_info_alter_order_payment_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': '訂單', 'verbose_name_plural': '訂單列表'},
        ),
        migrations.AddField(
            model_name='order',
            name='logistics_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='物流單號'),
        ),
        migrations.AddField(
            model_name='order',
            name='logistics_info',
            field=models.TextField(blank=True, null=True, verbose_name='物流資訊'),
        ),
        migrations.AddField(
            model_name='order',
            name='logistics_status',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='物流狀態'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(default='home_delivery', max_length=20, verbose_name='物流方式'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='訂單編號'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_info',
            field=models.TextField(blank=True, null=True, verbose_name='付款資訊'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash_on_delivery', '貨到付款')], default='cash_on_delivery', max_length=20, verbose_name='付款方式'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.CharField(max_length=255, verbose_name='收件地址'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_name',
            field=models.CharField(max_length=100, verbose_name='收件人姓名'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_note',
            field=models.TextField(blank=True, null=True, verbose_name='訂單備註'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_phone',
            field=models.CharField(max_length=20, verbose_name='收件人電話'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', '待付款'), ('paid', '已付款'), ('shipped', '已出貨'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='狀態'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用戶'),
        ),
    ]
