# Generated by Django 5.1.6 on 2025-03-19 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_system', '0008_alter_order_options_order_logistics_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='訂單編號'),
        ),
    ]
